server:
  servlet:
    context-path: /hometop

spring:
  application:
    name: onepass

  profiles:
    active: dev

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  thymeleaf:
    encoding: UTF-8