server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  # SQL 초기화 스크립트 설정
  sql:
    init:
      mode: never   # never: 스크립트 실행 안 함 | always: 매 기동 시 실행
      encoding: UTF-8

  jpa:
    defer-datasource-initalization: true    # datasource 초기화 후 data.sql 실행(순서 보장)
    hibernate:
      ddl-auto: update
    show-sql: false

  thymeleaf:
    cache: false

logging:
  level:
    root: INFO      # 전체 기본 로그 레벨
    com.hometalk: DEBUG   # 프로젝트 패키지 - 상세 로그 출력
    orghibernate.SQL: DEBUG     # hibernate SQL 쿼리 로그
